
export const provincesData = [
    { id: '1', name: 'An Giang' },
    { id: '2', name: 'Bà Rịa - Vũng Tàu' },
    { id: '3', name: 'Bắc Giang' },
    { id: '4', name: 'Bắc Kạn' },
    { id: '5', name: 'Bạc Liêu' },
    { id: '6', name: 'Bắc Ninh' },
    { id: '7', name: 'Bến Tre' },
    { id: '8', name: 'Bình Định' },
    { id: '9', name: 'Bình Dương' },
    { id: '10', name: 'Bình Phước' },
    { id: '11', name: 'Bình Thuận' },
    { id: '12', name: 'Cà Mau' },
    { id: '13', name: 'Cần Thơ' },
    { id: '14', name: 'Cao Bằng' },
    { id: '15', name: 'Đà Nẵng' },
    { id: '16', name: 'Đắk Lắk' },
    { id: '17', name: 'Đắk Nông' },
    { id: '18', name: 'Điện Biên' },
    { id: '19', name: 'Đồng Nai' },
    { id: '20', name: 'Đồng Tháp' },
    { id: '21', name: 'Gia Lai' },
    { id: '22', name: 'Hà Giang' },
    { id: '23', name: 'Hà Nam' },
    { id: '24', name: 'Hà Nội' },
    { id: '25', name: 'Hà Tĩnh' },
    { id: '26', name: 'Hải Dương' },
    { id: '27', name: 'Hải Phòng' },
    { id: '28', name: 'Hậu Giang' },
    { id: '29', name: 'Hòa Bình' },
    { id: '30', name: 'Hưng Yên' },
    { id: '31', name: 'Khánh Hòa' },
    { id: '32', name: 'Kiên Giang' },
    { id: '33', name: 'Kon Tum' },
    { id: '34', name: 'Lai Châu' },
    { id: '35', name: 'Lâm Đồng' },
    { id: '36', name: 'Lạng Sơn' },
    { id: '37', name: 'Lào Cai' },
    { id: '38', name: 'Long An' },
    { id: '39', name: 'Nam Định' },
    { id: '40', name: 'Nghệ An' },
    { id: '41', name: 'Ninh Bình' },
    { id: '42', name: 'Ninh Thuận' },
    { id: '43', name: 'Phú Thọ' },
    { id: '44', name: 'Phú Yên' },
    { id: '45', name: 'Quảng Bình' },
    { id: '46', name: 'Quảng Nam' },
    { id: '47', name: 'Quảng Ngãi' },
    { id: '48', name: 'Quảng Ninh' },
    { id: '49', name: 'Quảng Trị' },
    { id: '50', name: 'Sóc Trăng' },
    { id: '51', name: 'Sơn La' },
    { id: '52', name: 'Tây Ninh' },
    { id: '53', name: 'Thái Bình' },
    { id: '54', name: 'Thái Nguyên' },
    { id: '55', name: 'Thanh Hóa' },
    { id: '56', name: 'Thừa Thiên Huế' },
    { id: '57', name: 'Tiền Giang' },
    { id: '58', name: 'TP. Hồ Chí Minh' },
    { id: '59', name: 'Trà Vinh' },
    { id: '60', name: 'Tuyên Quang' },
    { id: '61', name: 'Vĩnh Long' },
    { id: '62', name: 'Vĩnh Phúc' },
    { id: '63', name: 'Yên Bái' }
];

export const districtsData = {
    '1': [
        { id: '101', name: 'Thành phố Long Xuyên' },
        { id: '102', name: 'Huyện An Phú' },
        { id: '103', name: 'Huyện Châu Phú' },
        { id: '104', name: 'Huyện Châu Thành' },
        { id: '105', name: 'Huyện Chợ Mới' },
        { id: '106', name: 'Huyện Phú Tân' },
        { id: '107', name: 'Thành phố Châu Đốc' },
        { id: '108', name: 'Huyện Tịnh Biên' },
        { id: '109', name: 'Huyện Tri Tôn' },
        { id: '110', name: 'Huyện Thoại Sơn' }
    ],
    '2': [
        { id: '201', name: 'Thành phố Vũng Tàu' },
        { id: '202', name: 'Thành phố Bà Rịa' },
        { id: '203', name: 'Huyện Châu Đức' },
        { id: '204', name: 'Huyện Côn Đảo' },
        { id: '205', name: 'Huyện Đất Đỏ' },
        { id: '206', name: 'Huyện Long Điền' },
        { id: '207', name: 'Thị xã Phú Mỹ' },
        { id: '208', name: 'Huyện Xuyên Mộc' }
    ],
    '3': [
        { id: '301', name: 'Thành phố Bắc Giang' },
        { id: '302', name: 'Huyện Hiệp Hòa' },
        { id: '303', name: 'Huyện Lạng Giang' },
        { id: '304', name: 'Huyện Lục Nam' },
        { id: '305', name: 'Huyện Lục Ngạn' },
        { id: '306', name: 'Huyện Sơn Động' },
        { id: '307', name: 'Huyện Tân Yên' },
        { id: '308', name: 'Huyện Việt Yên' },
        { id: '309', name: 'Huyện Yên Dũng' },
        { id: '310', name: 'Huyện Yên Thế' }
    ],
    '4': [
        { id: '401', name: 'Thành phố Bắc Kạn' },
        { id: '402', name: 'Huyện Ba Bể' },
        { id: '403', name: 'Huyện Bạch Thông' },
        { id: '404', name: 'Huyện Chợ Đồn' },
        { id: '405', name: 'Huyện Chợ Mới' },
        { id: '406', name: 'Huyện Na Rì' },
        { id: '407', name: 'Huyện Ngân Sơn' },
        { id: '408', name: 'Huyện Pác Nặm' }
    ],
    '5': [
        { id: '501', name: 'Thành phố Bạc Liêu' },
        { id: '502', name: 'Huyện Đông Hải' },
        { id: '503', name: 'Huyện Giá Rai' },
        { id: '504', name: 'Huyện Hòa Bình' },
        { id: '505', name: 'Huyện Hồng Dân' },
        { id: '506', name: 'Huyện Phước Long' },
        { id: '507', name: 'Huyện Vĩnh Lợi' }
    ],
    '6': [
        { id: '601', name: 'Thành phố Bắc Ninh' },
        { id: '602', name: 'Huyện Gia Bình' },
        { id: '603', name: 'Huyện Lương Tài' },
        { id: '604', name: 'Huyện Quế Võ' },
        { id: '605', name: 'Huyện Thuận Thành' },
        { id: '606', name: 'Thị xã Từ Sơn' },
        { id: '607', name: 'Huyện Yên Phong' },
        { id: '608', name: 'Huyện Tiên Du' }
    ],
    '7': [
        { id: '701', name: 'Thành phố Bến Tre' },
        { id: '702', name: 'Huyện Ba Tri' },
        { id: '703', name: 'Huyện Bình Đại' },
        { id: '704', name: 'Huyện Châu Thành' },
        { id: '705', name: 'Huyện Chợ Lách' },
        { id: '706', name: 'Huyện Giồng Trôm' },
        { id: '707', name: 'Huyện Mỏ Cày Bắc' },
        { id: '708', name: 'Huyện Mỏ Cày Nam' },
        { id: '709', name: 'Huyện Thạnh Phú' }
    ],
    '8': [
        { id: '801', name: 'Thành phố Quy Nhơn' },
        { id: '802', name: 'Huyện An Lão' },
        { id: '803', name: 'Huyện Hoài Ân' },
        { id: '804', name: 'Huyện Hoài Nhơn' },
        { id: '805', name: 'Huyện Phù Cát' },
        { id: '806', name: 'Huyện Phù Mỹ' },
        { id: '807', name: 'Huyện Tây Sơn' },
        { id: '808', name: 'Huyện Tuy Phước' },
        { id: '809', name: 'Huyện Vân Canh' },
        { id: '810', name: 'Huyện Vĩnh Thạnh' }
    ],
    '9': [
        { id: '901', name: 'Thành phố Thủ Dầu Một' },
        { id: '902', name: 'Thị xã Bến Cát' },
        { id: '903', name: 'Thị xã Dĩ An' },
        { id: '904', name: 'Thị xã Tân Uyên' },
        { id: '905', name: 'Thị xã Thuận An' },
        { id: '906', name: 'Huyện Bàu Bàng' },
        { id: '907', name: 'Huyện Bắc Tân Uyên' },
        { id: '908', name: 'Huyện Dầu Tiếng' },
        { id: '909', name: 'Huyện Phú Giáo' }
    ],
    '10': [
        { id: '1001', name: 'Thành phố Đồng Xoài' },
        { id: '1002', name: 'Thị xã Bình Long' },
        { id: '1003', name: 'Thị xã Phước Long' },
        { id: '1004', name: 'Huyện Bù Đăng' },
        { id: '1005', name: 'Huyện Bù Đốp' },
        { id: '1006', name: 'Huyện Bù Gia Mập' },
        { id: '1007', name: 'Huyện Chơn Thành' },
        { id: '1008', name: 'Huyện Đồng Phú' },
        { id: '1009', name: 'Huyện Hớn Quản' },
        { id: '1010', name: 'Huyện Lộc Ninh' },
        { id: '1011', name: 'Huyện Phú Riềng' }
    ],
    '11': [
        { id: '1101', name: 'Thành phố Phan Thiết' },
        { id: '1102', name: 'Thị xã La Gi' },
        { id: '1103', name: 'Huyện Bắc Bình' },
        { id: '1104', name: 'Huyện Đức Linh' },
        { id: '1105', name: 'Huyện Hàm Tân' },
        { id: '1106', name: 'Huyện Hàm Thuận Bắc' },
        { id: '1107', name: 'Huyện Hàm Thuận Nam' },
        { id: '1108', name: 'Huyện Phú Quý' },
        { id: '1109', name: 'Huyện Tánh Linh' },
        { id: '1110', name: 'Huyện Tuy Phong' }
    ],
    '12': [
        { id: '1201', name: 'Thành phố Cà Mau' },
        { id: '1202', name: 'Huyện Cái Nước' },
        { id: '1203', name: 'Huyện Đầm Dơi' },
        { id: '1204', name: 'Huyện Năm Căn' },
        { id: '1205', name: 'Huyện Ngọc Hiển' },
        { id: '1206', name: 'Huyện Phú Tân' },
        { id: '1207', name: 'Huyện Thới Bình' },
        { id: '1208', name: 'Huyện Trần Văn Thời' },
        { id: '1209', name: 'Huyện U Minh' }
    ],
    '13': [
        { id: '1301', name: 'Quận Ninh Kiều' },
        { id: '1302', name: 'Quận Bình Thủy' },
        { id: '1303', name: 'Quận Cái Răng' },
        { id: '1304', name: 'Quận Ô Môn' },
        { id: '1305', name: 'Quận Thốt Nốt' },
        { id: '1306', name: 'Huyện Cờ Đỏ' },
        { id: '1307', name: 'Huyện Phong Điền' },
        { id: '1308', name: 'Huyện Thới Lai' },
        { id: '1309', name: 'Huyện Vĩnh Thạnh' }
    ],
    '14': [
        { id: '1401', name: 'Thành phố Cao Bằng' },
        { id: '1402', name: 'Huyện Bảo Lạc' },
        { id: '1403', name: 'Huyện Bảo Lâm' },
        { id: '1404', name: 'Huyện Hạ Lang' },
        { id: '1405', name: 'Huyện Hà Quảng' },
        { id: '1406', name: 'Huyện Hòa An' },
        { id: '1407', name: 'Huyện Nguyên Bình' },
        { id: '1408', name: 'Huyện Phục Hòa' },
        { id: '1409', name: 'Huyện Quảng Hòa' },
        { id: '1410', name: 'Huyện Thạch An' },
        { id: '1411', name: 'Huyện Trùng Khánh' }
    ],
    '15': [
        { id: '1501', name: 'Quận Hải Châu' },
        { id: '1502', name: 'Quận Cẩm Lệ' },
        { id: '1503', name: 'Quận Liên Chiểu' },
        { id: '1504', name: 'Quận Ngũ Hành Sơn' },
        { id: '1505', name: 'Quận Sơn Trà' },
        { id: '1506', name: 'Quận Thanh Khê' },
        { id: '1507', name: 'Huyện Hòa Vang' },
        { id: '1508', name: 'Huyện Hoàng Sa' }
    ],
    '16': [
        { id: '1601', name: 'Thành phố Buôn Ma Thuột' },
        { id: '1602', name: 'Huyện Buôn Đôn' },
        { id: '1603', name: 'Huyện Cư Kuin' },
        { id: '1604', name: 'Huyện Cư M\'gar' },
        { id: '1605', name: 'Huyện Ea H\'leo' },
        { id: '1606', name: 'Huyện Ea Kar' },
        { id: '1607', name: 'Huyện Ea Súp' },
        { id: '1608', name: 'Huyện Krông Ana' },
        { id: '1609', name: 'Huyện Krông Bông' },
        { id: '1610', name: 'Huyện Krông Buk' },
        { id: '1611', name: 'Huyện Krông Năng' },
        { id: '1612', name: 'Huyện Krông Pắc' },
        { id: '1613', name: 'Huyện Lăk' },
        { id: '1614', name: 'Thị xã Buôn Hồ' }
    ],
    '17': [
        { id: '1701', name: 'Thành phố Gia Nghĩa' },
        { id: '1702', name: 'Huyện Cư Jút' },
        { id: '1703', name: 'Huyện Đắk Glong' },
        { id: '1704', name: 'Huyện Đắk Mil' },
        { id: '1705', name: 'Huyện Đắk R\'Lấp' },
        { id: '1706', name: 'Huyện Đắk Song' },
        { id: '1707', name: 'Huyện Krông Nô' },
        { id: '1708', name: 'Huyện Tuy Đức' }
    ],
    '18': [
        { id: '1801', name: 'Thành phố Điện Biên Phủ' },
        { id: '1802', name: 'Thị xã Mường Lay' },
        { id: '1803', name: 'Huyện Điện Biên' },
        { id: '1804', name: 'Huyện Điện Biên Đông' },
        { id: '1805', name: 'Huyện Mường Ảng' },
        { id: '1806', name: 'Huyện Mường Chà' },
        { id: '1807', name: 'Huyện Mường Nhé' },
        { id: '1808', name: 'Huyện Nậm Pồ' },
        { id: '1809', name: 'Huyện Tủa Chùa' },
        { id: '1810', name: 'Huyện Tuần Giáo' }
    ],
    '19': [
        { id: '1901', name: 'Thành phố Biên Hòa' },
        { id: '1902', name: 'Thành phố Long Khánh' },
        { id: '1903', name: 'Huyện Cẩm Mỹ' },
        { id: '1904', name: 'Huyện Định Quán' },
        { id: '1905', name: 'Huyện Long Thành' },
        { id: '1906', name: 'Huyện Nhơn Trạch' },
        { id: '1907', name: 'Huyện Tân Phú' },
        { id: '1908', name: 'Huyện Thống Nhất' },
        { id: '1909', name: 'Huyện Trảng Bom' },
        { id: '1910', name: 'Huyện Vĩnh Cửu' },
        { id: '1911', name: 'Huyện Xuân Lộc' }
    ],
    '20': [
        { id: '2001', name: 'Thành phố Cao Lãnh' },
        { id: '2002', name: 'Thành phố Sa Đéc' },
        { id: '2003', name: 'Thị xã Hồng Ngự' },
        { id: '2004', name: 'Huyện Cao Lãnh' },
        { id: '2005', name: 'Huyện Châu Thành' },
        { id: '2006', name: 'Huyện Hồng Ngự' },
        { id: '2007', name: 'Huyện Lai Vung' },
        { id: '2008', name: 'Huyện Lấp Vò' },
        { id: '2009', name: 'Huyện Tam Nông' },
        { id: '2010', name: 'Huyện Tân Hồng' },
        { id: '2011', name: 'Huyện Thanh Bình' },
        { id: '2012', name: 'Huyện Tháp Mười' }
    ],
    '21': [
        { id: '2101', name: 'Thành phố Pleiku' },
        { id: '2102', name: 'Thị xã An Khê' },
        { id: '2103', name: 'Thị xã Ayun Pa' },
        { id: '2104', name: 'Huyện Chư Păh' },
        { id: '2105', name: 'Huyện Chư Prông' },
        { id: '2106', name: 'Huyện Chư Pưh' },
        { id: '2107', name: 'Huyện Đăk Đoa' },
        { id: '2108', name: 'Huyện Đăk Pơ' },
        { id: '2109', name: 'Huyện Đức Cơ' },
        { id: '2110', name: 'Huyện Ia Grai' },
        { id: '2111', name: 'Huyện Ia Pa' },
        { id: '2112', name: 'Huyện Kbang' },
        { id: '2113', name: 'Huyện Kông Chro' },
        { id: '2114', name: 'Huyện Krông Pa' },
        { id: '2115', name: 'Huyện Mang Yang' },
        { id: '2116', name: 'Huyện Phú Thiện' }
    ],
    '22': [
        { id: '2201', name: 'Thành phố Hà Giang' },
        { id: '2202', name: 'Huyện Bắc Mê' },
        { id: '2203', name: 'Huyện Bắc Quang' },
        { id: '2204', name: 'Huyện Đồng Văn' },
        { id: '2205', name: 'Huyện Hoàng Su Phì' },
        { id: '2206', name: 'Huyện Mèo Vạc' },
        { id: '2207', name: 'Huyện Quản Bạ' },
        { id: '2208', name: 'Huyện Quang Bình' },
        { id: '2209', name: 'Huyện Vị Xuyên' },
        { id: '2210', name: 'Huyện Xín Mần' },
        { id: '2211', name: 'Huyện Yên Minh' }
    ],
    '23': [
        { id: '2301', name: 'Thành phố Phủ Lý' },
        { id: '2302', name: 'Thị xã Duy Tiên' },
        { id: '2303', name: 'Huyện Bình Lục' },
        { id: '2304', name: 'Huyện Kim Bảng' },
        { id: '2305', name: 'Huyện Lý Nhân' },
        { id: '2306', name: 'Huyện Thanh Liêm' }
    ],
    '24': [
        { id: '2401', name: 'Quận Ba Đình' },
        { id: '2402', name: 'Quận Hoàn Kiếm' },
        { id: '2403', name: 'Quận Đống Đa' },
        { id: '2404', name: 'Quận Hai Bà Trưng' },
        { id: '2405', name: 'Quận Hoàng Mai' },
        { id: '2406', name: 'Quận Long Biên' },
        { id: '2407', name: 'Quận Thanh Xuân' },
        { id: '2408', name: 'Quận Cầu Giấy' },
        { id: '2409', name: 'Quận Tây Hồ' },
        { id: '2410', name: 'Quận Nam Từ Liêm' },
        { id: '2411', name: 'Quận Bắc Từ Liêm' },
        { id: '2412', name: 'Thị xã Sơn Tây' },
        { id: '2413', name: 'Huyện Ba Vì' },
        { id: '2414', name: 'Huyện Chương Mỹ' },
        { id: '2415', name: 'Huyện Đan Phượng' },
        { id: '2416', name: 'Huyện Đông Anh' },
        { id: '2417', name: 'Huyện Gia Lâm' },
        { id: '2418', name: 'Huyện Hoài Đức' },
        { id: '2419', name: 'Huyện Mê Linh' },
        { id: '2420', name: 'Huyện Mỹ Đức' },
        { id: '2421', name: 'Huyện Phú Xuyên' },
        { id: '2422', name: 'Huyện Phúc Thọ' },
        { id: '2423', name: 'Huyện Quốc Oai' },
        { id: '2424', name: 'Huyện Sóc Sơn' },
        { id: '2425', name: 'Huyện Thạch Thất' },
        { id: '2426', name: 'Huyện Thanh Oai' },
        { id: '2427', name: 'Huyện Thanh Trì' },
        { id: '2428', name: 'Huyện Thường Tín' },
        { id: '2429', name: 'Huyện Ứng Hòa' }
    ],
    '25': [
        { id: '2501', name: 'Thành phố Hà Tĩnh' },
        { id: '2502', name: 'Thị xã Hồng Lĩnh' },
        { id: '2503', name: 'Thị xã Kỳ Anh' },
        { id: '2504', name: 'Huyện Cẩm Xuyên' },
        { id: '2505', name: 'Huyện Can Lộc' },
        { id: '2506', name: 'Huyện Đức Thọ' },
        { id: '2507', name: 'Huyện Hương Khê' },
        { id: '2508', name: 'Huyện Hương Sơn' },
        { id: '2509', name: 'Huyện Kỳ Anh' },
        { id: '2510', name: 'Huyện Lộc Hà' },
        { id: '2511', name: 'Huyện Nghi Xuân' },
        { id: '2512', name: 'Huyện Thạch Hà' },
        { id: '2513', name: 'Huyện Vũ Quang' }
    ],
    '26': [
        { id: '2601', name: 'Thành phố Hải Dương' },
        { id: '2602', name: 'Thị xã Kinh Môn' },
        { id: '2603', name: 'Huyện Bình Giang' },
        { id: '2604', name: 'Huyện Cẩm Giàng' },
        { id: '2605', name: 'Huyện Gia Lộc' },
        { id: '2606', name: 'Huyện Kim Thành' },
        { id: '2607', name: 'Huyện Nam Sách' },
        { id: '2608', name: 'Huyện Ninh Giang' },
        { id: '2609', name: 'Huyện Thanh Hà' },
        { id: '2610', name: 'Huyện Thanh Miện' },
        { id: '2611', name: 'Huyện Tứ Kỳ' }
    ],
    '27': [
        { id: '2701', name: 'Quận Hồng Bàng' },
        { id: '2702', name: 'Quận Ngô Quyền' },
        { id: '2703', name: 'Quận Lê Chân' },
        { id: '2704', name: 'Quận Hải An' },
        { id: '2705', name: 'Quận Kiến An' },
        { id: '2706', name: 'Quận Đồ Sơn' },
        { id: '2707', name: 'Quận Dương Kinh' },
        { id: '2708', name: 'Huyện An Dương' },
        { id: '2709', name: 'Huyện An Lão' },
        { id: '2710', name: 'Huyện Bạch Long Vĩ' },
        { id: '2711', name: 'Huyện Cát Hải' },
        { id: '2712', name: 'Huyện Kiến Thụy' },
        { id: '2713', name: 'Huyện Thủy Nguyên' },
        { id: '2714', name: 'Huyện Tiên Lãng' },
        { id: '2715', name: 'Huyện Vĩnh Bảo' }
    ],
    '28': [
        { id: '2801', name: 'Thành phố Vị Thanh' },
        { id: '2802', name: 'Thị xã Long Mỹ' },
        { id: '2803', name: 'Huyện Châu Thành' },
        { id: '2804', name: 'Huyện Châu Thành A' },
        { id: '2805', name: 'Huyện Long Mỹ' },
        { id: '2806', name: 'Huyện Phụng Hiệp' },
        { id: '2807', name: 'Huyện Vị Thủy' }
    ],
    '29': [
        { id: '2901', name: 'Thành phố Hòa Bình' },
        { id: '2902', name: 'Huyện Cao Phong' },
        { id: '2903', name: 'Huyện Đà Bắc' },
        { id: '2904', name: 'Huyện Kim Bôi' },
        { id: '2905', name: 'Huyện Lạc Sơn' },
        { id: '2906', name: 'Huyện Lạc Thủy' },
        { id: '2907', name: 'Huyện Lương Sơn' },
        { id: '2908', name: 'Huyện Mai Châu' },
        { id: '2909', name: 'Huyện Tân Lạc' },
        { id: '2910', name: 'Huyện Yên Thủy' }
    ],
    '30': [
        { id: '3001', name: 'Thành phố Hưng Yên' },
        { id: '3002', name: 'Huyện Ân Thi' },
        { id: '3003', name: 'Huyện Khoái Châu' },
        { id: '3004', name: 'Huyện Kim Động' },
        { id: '3005', name: 'Huyện Mỹ Hào' },
        { id: '3006', name: 'Huyện Phù Cừ' },
        { id: '3007', name: 'Huyện Tiên Lữ' },
        { id: '3008', name: 'Huyện Văn Giang' },
        { id: '3009', name: 'Huyện Văn Lâm' },
        { id: '3010', name: 'Huyện Yên Mỹ' }
    ],
    '31': [
        { id: '3101', name: 'Thành phố Nha Trang' },
        { id: '3102', name: 'Thành phố Cam Ranh' },
        { id: '3103', name: 'Huyện Cam Lâm' },
        { id: '3104', name: 'Huyện Diên Khánh' },
        { id: '3105', name: 'Huyện Khánh Sơn' },
        { id: '3106', name: 'Huyện Khánh Vĩnh' },
        { id: '3107', name: 'Thị xã Ninh Hòa' },
        { id: '3108', name: 'Huyện Trường Sa' },
        { id: '3109', name: 'Huyện Vạn Ninh' }
    ],
    '32': [
        { id: '3201', name: 'Thành phố Rạch Giá' },
        { id: '3202', name: 'Thành phố Hà Tiên' },
        { id: '3203', name: 'Huyện An Biên' },
        { id: '3204', name: 'Huyện An Minh' },
        { id: '3205', name: 'Huyện Châu Thành' },
        { id: '3206', name: 'Huyện Giang Thành' },
        { id: '3207', name: 'Huyện Giồng Riềng' },
        { id: '3208', name: 'Huyện Gò Quao' },
        { id: '3209', name: 'Huyện Hòn Đất' },
        { id: '3210', name: 'Huyện Kiên Hải' },
        { id: '3211', name: 'Huyện Kiên Lương' },
        { id: '3212', name: 'Huyện Phú Quốc' },
        { id: '3213', name: 'Huyện Tân Hiệp' },
        { id: '3214', name: 'Huyện U Minh Thượng' },
        { id: '3215', name: 'Huyện Vĩnh Thuận' }
    ],
    '33': [
        { id: '3301', name: 'Thành phố Kon Tum' },
        { id: '3302', name: 'Huyện Đăk Glei' },
        { id: '3303', name: 'Huyện Đăk Hà' },
        { id: '3304', name: 'Huyện Đăk Tô' },
        { id: '3305', name: 'Huyện Ia H\'Drai' },
        { id: '3306', name: 'Huyện Kon Plông' },
        { id: '3307', name: 'Huyện Kon Rẫy' },
        { id: '3308', name: 'Huyện Ngọc Hồi' },
        { id: '3309', name: 'Huyện Sa Thầy' },
        { id: '3310', name: 'Huyện Tu Mơ Rông' }
    ],
    '34': [
        { id: '3401', name: 'Thành phố Lai Châu' },
        { id: '3402', name: 'Huyện Mường Tè' },
        { id: '3403', name: 'Huyện Nậm Nhùn' },
        { id: '3404', name: 'Huyện Phong Thổ' },
        { id: '3405', name: 'Huyện Sìn Hồ' },
        { id: '3406', name: 'Huyện Tân Uyên' },
        { id: '3407', name: 'Huyện Than Uyên' },
        { id: '3408', name: 'Huyện Tam Đường' }
    ],
    '35': [
        { id: '3501', name: 'Thành phố Đà Lạt' },
        { id: '3502', name: 'Thành phố Bảo Lộc' },
        { id: '3503', name: 'Huyện Bảo Lâm' },
        { id: '3504', name: 'Huyện Cát Tiên' },
        { id: '3505', name: 'Huyện Đạ Huoai' },
        { id: '3506', name: 'Huyện Đạ Tẻh' },
        { id: '3507', name: 'Huyện Đam Rông' },
        { id: '3508', name: 'Huyện Di Linh' },
        { id: '3509', name: 'Huyện Đơn Dương' },
        { id: '3510', name: 'Huyện Đức Trọng' },
        { id: '3511', name: 'Huyện Lạc Dương' },
        { id: '3512', name: 'Huyện Lâm Hà' }
    ],
    '36': [
        { id: '3601', name: 'Thành phố Lạng Sơn' },
        { id: '3602', name: 'Huyện Bắc Sơn' },
        { id: '3603', name: 'Huyện Bình Gia' },
        { id: '3604', name: 'Huyện Cao Lộc' },
        { id: '3605', name: 'Huyện Chi Lăng' },
        { id: '3606', name: 'Huyện Đình Lập' },
        { id: '3607', name: 'Huyện Hữu Lũng' },
        { id: '3608', name: 'Huyện Lộc Bình' },
        { id: '3609', name: 'Huyện Tràng Định' },
        { id: '3610', name: 'Huyện Văn Lãng' },
        { id: '3611', name: 'Huyện Văn Quan' }
    ],
    '37': [
        { id: '3701', name: 'Thành phố Lào Cai' },
        { id: '3702', name: 'Huyện Bắc Hà' },
        { id: '3703', name: 'Huyện Bảo Thắng' },
        { id: '3704', name: 'Huyện Bảo Yên' },
        { id: '3705', name: 'Huyện Bát Xát' },
        { id: '3706', name: 'Huyện Mường Khương' },
        { id: '3707', name: 'Huyện Sa Pa' },
        { id: '3708', name: 'Huyện Si Ma Cai' },
        { id: '3709', name: 'Huyện Văn Bàn' }
    ],
    '38': [
        { id: '3801', name: 'Thành phố Tân An' },
        { id: '3802', name: 'Thị xã Kiến Tường' },
        { id: '3803', name: 'Huyện Bến Lức' },
        { id: '3804', name: 'Huyện Cần Đước' },
        { id: '3805', name: 'Huyện Cần Giuộc' },
        { id: '3806', name: 'Huyện Châu Thành' },
        { id: '3807', name: 'Huyện Đức Hòa' },
        { id: '3808', name: 'Huyện Đức Huệ' },
        { id: '3809', name: 'Huyện Mộc Hóa' },
        { id: '3810', name: 'Huyện Tân Hưng' },
        { id: '3811', name: 'Huyện Tân Thạnh' },
        { id: '3812', name: 'Huyện Tân Trụ' },
        { id: '3813', name: 'Huyện Thạnh Hóa' },
        { id: '3814', name: 'Huyện Thủ Thừa' },
        { id: '3815', name: 'Huyện Vĩnh Hưng' }
    ],
    '39': [
        { id: '3901', name: 'Thành phố Nam Định' },
        { id: '3902', name: 'Huyện Giao Thủy' },
        { id: '3903', name: 'Huyện Hải Hậu' },
        { id: '3904', name: 'Huyện Mỹ Lộc' },
        { id: '3905', name: 'Huyện Nam Trực' },
        { id: '3906', name: 'Huyện Nghĩa Hưng' },
        { id: '3907', name: 'Huyện Trực Ninh' },
        { id: '3908', name: 'Huyện Vụ Bản' },
        { id: '3909', name: 'Huyện Xuân Trường' },
        { id: '3910', name: 'Huyện Ý Yên' }
    ],
    '40': [
        { id: '4001', name: 'Thành phố Vinh' },
        { id: '4002', name: 'Thị xã Cửa Lò' },
        { id: '4003', name: 'Thị xã Hoàng Mai' },
        { id: '4004', name: 'Thị xã Thái Hòa' },
        { id: '4005', name: 'Huyện Anh Sơn' },
        { id: '4006', name: 'Huyện Con Cuông' },
        { id: '4007', name: 'Huyện Diễn Châu' },
        { id: '4008', name: 'Huyện Đô Lương' },
        { id: '4009', name: 'Huyện Hưng Nguyên' },
        { id: '4010', name: 'Huyện Kỳ Sơn' },
        { id: '4011', name: 'Huyện Nam Đàn' },
        { id: '4012', name: 'Huyện Nghi Lộc' },
        { id: '4013', name: 'Huyện Nghĩa Đàn' },
        { id: '4014', name: 'Huyện Quế Phong' },
        { id: '4015', name: 'Huyện Quỳ Châu' },
        { id: '4016', name: 'Huyện Quỳ Hợp' },
        { id: '4017', name: 'Huyện Quỳnh Lưu' },
        { id: '4018', name: 'Huyện Tân Kỳ' },
        { id: '4019', name: 'Huyện Thanh Chương' },
        { id: '4020', name: 'Huyện Tương Dương' },
        { id: '4021', name: 'Huyện Yên Thành' }
    ],
    '41': [
        { id: '4101', name: 'Thành phố Ninh Bình' },
        { id: '4102', name: 'Thành phố Tam Điệp' },
        { id: '4103', name: 'Huyện Gia Viễn' },
        { id: '4104', name: 'Huyện Hoa Lư' },
        { id: '4105', name: 'Huyện Kim Sơn' },
        { id: '4106', name: 'Huyện Nho Quan' },
        { id: '4107', name: 'Huyện Yên Khánh' },
        { id: '4108', name: 'Huyện Yên Mô' }
    ],
    '42': [
        { id: '4201', name: 'Thành phố Phan Rang-Tháp Chàm' },
        { id: '4202', name: 'Huyện Bác Ái' },
        { id: '4203', name: 'Huyện Ninh Hải' },
        { id: '4204', name: 'Huyện Ninh Phước' },
        { id: '4205', name: 'Huyện Ninh Sơn' },
        { id: '4206', name: 'Huyện Thuận Bắc' },
        { id: '4207', name: 'Huyện Thuận Nam' }
    ],
    '43': [
        { id: '4301', name: 'Thành phố Việt Trì' },
        { id: '4302', name: 'Thị xã Phú Thọ' },
        { id: '4303', name: 'Huyện Cẩm Khê' },
        { id: '4304', name: 'Huyện Đoan Hùng' },
        { id: '4305', name: 'Huyện Hạ Hòa' },
        { id: '4306', name: 'Huyện Lâm Thao' },
        { id: '4307', name: 'Huyện Phù Ninh' },
        { id: '4308', name: 'Huyện Tam Nông' },
        { id: '4309', name: 'Huyện Tân Sơn' },
        { id: '4310', name: 'Huyện Thanh Ba' },
        { id: '4311', name: 'Huyện Thanh Sơn' },
        { id: '4312', name: 'Huyện Thanh Thủy' },
        { id: '4313', name: 'Huyện Yên Lập' }
    ],
    '44': [
        { id: '4401', name: 'Thành phố Tuy Hòa' },
        { id: '4402', name: 'Thị xã Sông Cầu' },
        { id: '4403', name: 'Huyện Đông Hòa' },
        { id: '4404', name: 'Huyện Đồng Xuân' },
        { id: '4405', name: 'Huyện Phú Hòa' },
        { id: '4406', name: 'Huyện Sơn Hòa' },
        { id: '4407', name: 'Huyện Sông Hinh' },
        { id: '4408', name: 'Huyện Tây Hòa' },
        { id: '4409', name: 'Huyện Tuy An' }
    ],
    '45': [
        { id: '4501', name: 'Thành phố Đồng Hới' },
        { id: '4502', name: 'Thị xã Ba Đồn' },
        { id: '4503', name: 'Huyện Bố Trạch' },
        { id: '4504', name: 'Huyện Lệ Thủy' },
        { id: '4505', name: 'Huyện Minh Hóa' },
        { id: '4506', name: 'Huyện Quảng Ninh' },
        { id: '4507', name: 'Huyện Quảng Trạch' },
        { id: '4508', name: 'Huyện Tuyên Hóa' }
    ],
    '46': [
        { id: '4601', name: 'Thành phố Tam Kỳ' },
        { id: '4602', name: 'Thành phố Hội An' },
        { id: '4603', name: 'Thị xã Điện Bàn' },
        { id: '4604', name: 'Huyện Bắc Trà My' },
        { id: '4605', name: 'Huyện Duy Xuyên' },
        { id: '4606', name: 'Huyện Đông Giang' },
        { id: '4607', name: 'Huyện Đại Lộc' },
        { id: '4608', name: 'Huyện Hiệp Đức' },
        { id: '4609', name: 'Huyện Nam Giang' },
        { id: '4610', name: 'Huyện Nam Trà My' },
        { id: '4611', name: 'Huyện Nông Sơn' },
        { id: '4612', name: 'Huyện Núi Thành' },
        { id: '4613', name: 'Huyện Phú Ninh' },
        { id: '4614', name: 'Huyện Phước Sơn' },
        { id: '4615', name: 'Huyện Quế Sơn' },
        { id: '4616', name: 'Huyện Tây Giang' },
        { id: '4617', name: 'Huyện Thăng Bình' },
        { id: '4618', name: 'Huyện Tiên Phước' }
    ],
    '47': [
        { id: '4701', name: 'Thành phố Quảng Ngãi' },
        { id: '4702', name: 'Huyện Ba Tơ' },
        { id: '4703', name: 'Huyện Bình Sơn' },
        { id: '4704', name: 'Huyện Đức Phổ' },
        { id: '4705', name: 'Huyện Lý Sơn' },
        { id: '4706', name: 'Huyện Minh Long' },
        { id: '4707', name: 'Huyện Mộ Đức' },
        { id: '4708', name: 'Huyện Nghĩa Hành' },
        { id: '4709', name: 'Huyện Sơn Hà' },
        { id: '4710', name: 'Huyện Sơn Tây' },
        { id: '4711', name: 'Huyện Sơn Tịnh' },
        { id: '4712', name: 'Huyện Tây Trà' },
        { id: '4713', name: 'Huyện Trà Bồng' },
        { id: '4714', name: 'Huyện Tư Nghĩa' }
    ],
    '48': [
        { id: '4801', name: 'Thành phố Hạ Long' },
        { id: '4802', name: 'Thành phố Cẩm Phả' },
        { id: '4803', name: 'Thành phố Móng Cái' },
        { id: '4804', name: 'Thành phố Uông Bí' },
        { id: '4805', name: 'Huyện Ba Chẽ' },
        { id: '4806', name: 'Huyện Bình Liêu' },
        { id: '4807', name: 'Huyện Cô Tô' },
        { id: '4808', name: 'Huyện Đầm Hà' },
        { id: '4809', name: 'Huyện Đông Triều' },
        { id: '4810', name: 'Huyện Hải Hà' },
        { id: '4811', name: 'Huyện Hoành Bồ' },
        { id: '4812', name: 'Huyện Quảng Yên' },
        { id: '4813', name: 'Huyện Tiên Yên' },
        { id: '4814', name: 'Huyện Vân Đồn' }
    ],
    '49': [
        { id: '4901', name: 'Thành phố Đông Hà' },
        { id: '4902', name: 'Thị xã Quảng Trị' },
        { id: '4903', name: 'Huyện Cam Lộ' },
        { id: '4904', name: 'Huyện Cồn Cỏ' },
        { id: '4905', name: 'Huyện Đa Krông' },
        { id: '4906', name: 'Huyện Gio Linh' },
        { id: '4907', name: 'Huyện Hải Lăng' },
        { id: '4908', name: 'Huyện Hướng Hóa' },
        { id: '4909', name: 'Huyện Triệu Phong' },
        { id: '4910', name: 'Huyện Vĩnh Linh' }
    ],
    '50': [
        { id: '5001', name: 'Thành phố Sóc Trăng' },
        { id: '5002', name: 'Thị xã Ngã Năm' },
        { id: '5003', name: 'Thị xã Vĩnh Châu' },
        { id: '5004', name: 'Huyện Châu Thành' },
        { id: '5005', name: 'Huyện Cù Lao Dung' },
        { id: '5006', name: 'Huyện Kế Sách' },
        { id: '5007', name: 'Huyện Long Phú' },
        { id: '5008', name: 'Huyện Mỹ Tú' },
        { id: '5009', name: 'Huyện Mỹ Xuyên' },
        { id: '5010', name: 'Huyện Thạnh Trị' },
        { id: '5011', name: 'Huyện Trần Đề' }
    ],
    '51': [
        { id: '5101', name: 'Thành phố Sơn La' },
        { id: '5102', name: 'Huyện Bắc Yên' },
        { id: '5103', name: 'Huyện Mai Sơn' },
        { id: '5104', name: 'Huyện Mộc Châu' },
        { id: '5105', name: 'Huyện Mường La' },
        { id: '5106', name: 'Huyện Phù Yên' },
        { id: '5107', name: 'Huyện Quỳnh Nhai' },
        { id: '5108', name: 'Huyện Sông Mã' },
        { id: '5109', name: 'Huyện Sốp Cộp' },
        { id: '5110', name: 'Huyện Thuận Châu' },
        { id: '5111', name: 'Huyện Vân Hồ' },
        { id: '5112', name: 'Huyện Yên Châu' }
    ],
    '52': [
        { id: '5201', name: 'Thành phố Tây Ninh' },
        { id: '5202', name: 'Huyện Bến Cầu' },
        { id: '5203', name: 'Huyện Châu Thành' },
        { id: '5204', name: 'Huyện Dương Minh Châu' },
        { id: '5205', name: 'Huyện Gò Dầu' },
        { id: '5206', name: 'Huyện Hòa Thành' },
        { id: '5207', name: 'Huyện Tân Biên' },
        { id: '5208', name: 'Huyện Tân Châu' },
        { id: '5209', name: 'Huyện Trảng Bàng' }
    ],
    '53': [
        { id: '5301', name: 'Thành phố Thái Bình' },
        { id: '5302', name: 'Huyện Đông Hưng' },
        { id: '5303', name: 'Huyện Hưng Hà' },
        { id: '5304', name: 'Huyện Kiến Xương' },
        { id: '5305', name: 'Huyện Quỳnh Phụ' },
        { id: '5306', name: 'Huyện Thái Thụy' },
        { id: '5307', name: 'Huyện Tiền Hải' },
        { id: '5308', name: 'Huyện Vũ Thư' }
    ],
    '54': [
        { id: '5401', name: 'Thành phố Thái Nguyên' },
        { id: '5402', name: 'Thành phố Sông Công' },
        { id: '5403', name: 'Huyện Đại Từ' },
        { id: '5404', name: 'Huyện Định Hóa' },
        { id: '5405', name: 'Huyện Đồng Hỷ' },
        { id: '5406', name: 'Huyện Phổ Yên' },
        { id: '5407', name: 'Huyện Phú Bình' },
        { id: '5408', name: 'Huyện Phú Lương' },
        { id: '5409', name: 'Huyện Võ Nhai' }
    ],
    '55': [
        { id: '5501', name: 'Thành phố Thanh Hóa' },
        { id: '5502', name: 'Thị xã Bỉm Sơn' },
        { id: '5503', name: 'Thị xã Nghi Sơn' },
        { id: '5504', name: 'Huyện Bá Thước' },
        { id: '5505', name: 'Huyện Cẩm Thủy' },
        { id: '5506', name: 'Huyện Đông Sơn' },
        { id: '5507', name: 'Huyện Hà Trung' },
        { id: '5508', name: 'Huyện Hậu Lộc' },
        { id: '5509', name: 'Huyện Hoằng Hóa' },
        { id: '5510', name: 'Huyện Lang Chánh' },
        { id: '5511', name: 'Huyện Mường Lát' },
        { id: '5512', name: 'Huyện Nga Sơn' },
        { id: '5513', name: 'Huyện Ngọc Lặc' },
        { id: '5514', name: 'Huyện Như Thanh' },
        { id: '5515', name: 'Huyện Như Xuân' },
        { id: '5516', name: 'Huyện Nông Cống' },
        { id: '5517', name: 'Huyện Quan Hóa' },
        { id: '5518', name: 'Huyện Quan Sơn' },
        { id: '5519', name: 'Huyện Quảng Xương' },
        { id: '5520', name: 'Huyện Thạch Thành' },
        { id: '5521', name: 'Huyện Thiệu Hóa' },
        { id: '5522', name: 'Huyện Thọ Xuân' },
        { id: '5523', name: 'Huyện Thường Xuân' },
        { id: '5524', name: 'Huyện Triệu Sơn' },
        { id: '5525', name: 'Huyện Vĩnh Lộc' },
        { id: '5526', name: 'Huyện Yên Định' }
    ],
    '56': [
        { id: '5601', name: 'Thành phố Huế' },
        { id: '5602', name: 'Thị xã Hương Thủy' },
        { id: '5603', name: 'Thị xã Hương Trà' },
        { id: '5604', name: 'Huyện A Lưới' },
        { id: '5605', name: 'Huyện Nam Đông' },
        { id: '5606', name: 'Huyện Phong Điền' },
        { id: '5607', name: 'Huyện Phú Lộc' },
        { id: '5608', name: 'Huyện Phú Vang' },
        { id: '5609', name: 'Huyện Quảng Điền' }
    ],
    '57': [
        { id: '5701', name: 'Thành phố Mỹ Tho' },
        { id: '5702', name: 'Thị xã Cai Lậy' },
        { id: '5703', name: 'Thị xã Gò Công' },
        { id: '5704', name: 'Huyện Cái Bè' },
        { id: '5705', name: 'Huyện Châu Thành' },
        { id: '5706', name: 'Huyện Chợ Gạo' },
        { id: '5707', name: 'Huyện Gò Công Đông' },
        { id: '5708', name: 'Huyện Gò Công Tây' },
        { id: '5709', name: 'Huyện Tân Phú Đông' },
        { id: '5710', name: 'Huyện Tân Phước' }
    ],
    '58': [
        { id: '5801', name: 'Quận 1' },
        { id: '5802', name: 'Quận 2' },
        { id: '5803', name: 'Quận 3' },
        { id: '5804', name: 'Quận 4' },
        { id: '5805', name: 'Quận 5' },
        { id: '5806', name: 'Quận 6' },
        { id: '5807', name: 'Quận 7' },
        { id: '5808', name: 'Quận 8' },
        { id: '5809', name: 'Quận 9' },
        { id: '5810', name: 'Quận 10' },
        { id: '5811', name: 'Quận 11' },
        { id: '5812', name: 'Quận 12' },
        { id: '5813', name: 'Quận Bình Tân' },
        { id: '5814', name: 'Quận Bình Thạnh' },
        { id: '5815', name: 'Quận Gò Vấp' },
        { id: '5816', name: 'Quận Phú Nhuận' },
        { id: '5817', name: 'Quận Tân Bình' },
        { id: '5818', name: 'Quận Tân Phú' },
        { id: '5819', name: 'Quận Thủ Đức' },
        { id: '5820', name: 'Huyện Bình Chánh' },
        { id: '5821', name: 'Huyện Cần Giờ' },
        { id: '5822', name: 'Huyện Củ Chi' },
        { id: '5823', name: 'Huyện Hóc Môn' },
        { id: '5824', name: 'Huyện Nhà Bè' }
    ],
    '59': [
        { id: '5901', name: 'Thành phố Trà Vinh' },
        { id: '5902', name: 'Huyện Càng Long' },
        { id: '5903', name: 'Huyện Cầu Kè' },
        { id: '5904', name: 'Huyện Cầu Ngang' },
        { id: '5905', name: 'Huyện Châu Thành' },
        { id: '5906', name: 'Huyện Duyên Hải' },
        { id: '5907', name: 'Huyện Tiểu Cần' },
        { id: '5908', name: 'Huyện Trà Cú' },
        { id: '5909', name: 'Thị xã Duyên Hải' }
    ],
    '60': [
        { id: '6001', name: 'Thành phố Tuyên Quang' },
        { id: '6002', name: 'Huyện Chiêm Hóa' },
        { id: '6003', name: 'Huyện Hàm Yên' },
        { id: '6004', name: 'Huyện Lâm Bình' },
        { id: '6005', name: 'Huyện Na Hang' },
        { id: '6006', name: 'Huyện Sơn Dương' },
        { id: '6007', name: 'Huyện Yên Sơn' }
    ],
    '61': [
        { id: '6101', name: 'Thành phố Vĩnh Long' },
        { id: '6102', name: 'Huyện Bình Minh' },
        { id: '6103', name: 'Huyện Bình Tân' },
        { id: '6104', name: 'Huyện Long Hồ' },
        { id: '6105', name: 'Huyện Mang Thít' },
        { id: '6106', name: 'Huyện Tam Bình' },
        { id: '6107', name: 'Huyện Trà Ôn' },
        { id: '6108', name: 'Huyện Vũng Liêm' }
    ],
    '62': [
        { id: '6201', name: 'Thành phố Vĩnh Yên' },
        { id: '6202', name: 'Thị xã Phúc Yên' },
        { id: '6203', name: 'Huyện Bình Xuyên' },
        { id: '6204', name: 'Huyện Lập Thạch' },
        { id: '6205', name: 'Huyện Sông Lô' },
        { id: '6206', name: 'Huyện Tam Đảo' },
        { id: '6207', name: 'Huyện Tam Dương' },
        { id: '6208', name: 'Huyện Vĩnh Tường' },
        { id: '6209', name: 'Huyện Yên Lạc' }
    ],
    '63': [
        { id: '6301', name: 'Thành phố Yên Bái' },
        { id: '6302', name: 'Thị xã Nghĩa Lộ' },
        { id: '6303', name: 'Huyện Lục Yên' },
        { id: '6304', name: 'Huyện Mù Cang Chải' },
        { id: '6305', name: 'Huyện Trạm Tấu' },
        { id: '6306', name: 'Huyện Trấn Yên' },
        { id: '6307', name: 'Huyện Văn Chấn' },
        { id: '6308', name: 'Huyện Văn Yên' },
        { id: '6309', name: 'Huyện Yên Bình' }
    ]
};




